---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      network:
      - ["private_network", {ip: "192.168.33.60"}]

suites:
  - name: default
    run_list:
      - recipe[couchpotato::default]
    attributes:
